#!/bin/bash

if [ -f /etc/iiab/iiab.env ]
then
  . /etc/iiab/iiab.env
else
 echo "IIAB Config not found."
 echo "Please install Internet in a Box before installing the Admin Console."
 echo "Exiting."
 exit
fi

PLAYBOOK="iiab-admin.yml"
INVENTORY="ansible_hosts"

IIAB_ADMIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f $IIAB_ADMIN_DIR/$PLAYBOOK ]; then
 echo "Admin Console Playbook not found."
 echo "Please make sure you have cloned the iiab-admin git repo."
 echo "Exiting."
 exit
fi

cd $IIAB_ADMIN_DIR

# facts file for admin console, assumes iiab created directory
cp ./scripts/admin_facts.fact /etc/ansible/facts.d/admin_facts.fact

echo "Running local playbooks! "

# ARGS="--extra-vars '{\"target_base\":\"$IIAB_DIR\"}'"
#ARGS="target_base=$IIAB_DIR"

export ANSIBLE_LOG_PATH="$IIAB_ADMIN_DIR/admin-install.log"

#ansible-playbook -i $INVENTORY $PLAYBOOK --extra-vars "${ARGS}" --connection=local
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local

if [[ "$1" ==  "-n" ]]; then
  echo "WARNING: THIS CAN CAUSE PROBLEMS"
  echo "Only do this if a full install has already completed"
  echo "Skipping data setup"
else
  # Run various utilites to setup initial data
  echo "Downloading Catalogs and Building Local Data Files."

  iiab-get-kiwix-cat -v
  iiab-get-oer2go-cat
  iiab-make-kiwix-lib
  iiab-update-menus
fi

# Start CMDSRV
echo "(Re)Starting CMDSRV"
systemctl enable iiab-cmdsrv
systemctl restart iiab-cmdsrv
