#!/bin/bash

# Check for user and create if absent
rc=`mysql --execute "SELECT Password FROM mysql.user where Host = 'localhost' and User = 'iiab_commenter';"`

if [ "$rc" = "" ]; then
  mysql --execute "CREATE USER iiab_commenter@localhost IDENTIFIED BY 'g0adm1n';"
fi

# Create database and table
mysql < setup/comments-db.sql

echo 'database created'
