#!/usr/bin/python3

import time
import subprocess

t1 = time.time()

rc = subprocess.call(["wget", "http://cachefly.cachefly.net/10mb.test", "-q", "-O", "/dev/null"])

t2 = time.time()

if rc == 0:
    t3 = t2 - t1
    speed = 10/t3*8
    print ("Time for 10MB was %f seconds; Speed was %f Mbit/s" % (t3, speed))
else:
    print ("Speed Test Failed.")
