#!/bin/bash

CMDSRV_SCRIPTS="/opt/admin/cmdsrv/scripts"
if [ ! -f "$CMDSRV_SCRIPTS/upgrade-zims.py" ]; then
  echo "Admin Console not installed. Exiting."
  exit
fi
$CMDSRV_SCRIPTS/upgrade-zims.py "$@"
if [ $? -ne 0 ]; then
  echo "Update Zims Failed."
  exit 1
fi
exit
