#!/bin/bash

CMDSRV_SCRIPTS="{{ cmdsrv_dir }}/scripts"
$CMDSRV_SCRIPTS/get_kiwix_catalog -v

if [ $? -ne 0 ]; then
  echo "Getting the Kiwix Catalog Failed."
  echo "Please run iiab-get-kiwix-cat again later."
fi
exit
