#!/bin/bash

LOCK_PATH=/run/lock/iiab-menus
mkdir -p $LOCK_PATH

WAITLOCK="$LOCK_PATH/update-menus-wait.LCK";
RUNLOCK="$LOCK_PATH/update-menus-run.LCK";
UPDATE_MENUS="/opt/admin/cmdsrv//scripts/iiab_update_menus.py"

exec 202>$WAITLOCK;
exec 203>$RUNLOCK;

if flock -n -e 202; then :
  echo 'Waiting to run iiab_update_menus.py'
  # wait for up to 5 min
  flock -x -w 300 203
  flock -u 202 # unlock queue
  echo "Now running iiab_update_menus.py"
  $UPDATE_MENUS
else
  echo "Can't get wait lock for iiab_update_menus.py";
  exit 1;
fi
echo 'Finished running iiab_update_menus.py'
exit 0
