#!/bin/bash -x
# 9/29/2017

if [ -f /etc/systemd/system/xsce-cmdsrv.service ]; then
  systemctl stop xsce-cmdsrv
  rm /etc/systemd/system/xsce-cmdsrv.service
  systemctl daemon-reload
fi

rm -rf /opt/schoolserver/xsce_cmdsrv
rm -rf /opt/schoolserver/admin_console
